<<<<<<< origin/develop
sudo: required

dist: trusty

language: java

jdk:
  - oraclejdk8

addons:
    apt:
        packages:
        - oracle-java8-installer
        - git
        - libglpk-dev
        - libglpk-java

before_install:
  - echo glpkJava=$(dpkg -L libglpk-java | egrep 'libglpk_java.so$') > gradle.properties
  - echo glpk=$(dpkg -L libglpk-dev | egrep 'libglpk.so$') >> gradle.properties
=======
language: java
jdk:
  - oraclejdk8
>>>>>>> HEAD~132
