//helper functions, it turned out chrome doesn't support Math.sgn() 
function signum(x) {
    return (x < 0) ? -1 : 1;
}
function absolute(x) {
    return (x < 0) ? -x : x;
}
function drawPath(svg, path, startX, startY, endX, endY) {
    // get the path's stroke width (if one wanted to be  really precize, one could use half the stroke size)
    var stroke =  parseFloat(path.attr("stroke-width"));
    // check if the svg is big enough to draw the path, if not, set heigh/width
    if (svg.attr("height") <  endY)                 svg.attr("height", endY);
    if (svg.attr("width" ) < (startX + stroke) )    svg.attr("width", (startX + stroke));
    if (svg.attr("width" ) < (endX   + stroke) )    svg.attr("width", (endX   + stroke));
    
    var deltaX = (endX - startX) * 0.15;
    var deltaY = (endY - startY) * 0.15;
    // for further calculations which ever is the shortest distance
    var delta  =  deltaY < absolute(deltaX) ? deltaY : absolute(deltaX);
    // set sweep-flag (counter/clock-wise)
    // if start element is closer to the left edge,
    // draw the first arc counter-clockwise, and the second one clock-wise
    var arc1 = 0; var arc2 = 1;
    if (startX > endX) {
        arc1 = 1;
        arc2 = 0;
    }
    // draw tha pipe-like path
    // 1. move a bit down, 2. arch,  3. move a bit to the right, 4.arch, 5. move down to the end 
    path.attr("d",  "M"  + startX + " " + startY +
                    " V" + (startY + delta) +
                    " A" + delta + " " +  delta + " 0 0 " + arc1 + " " + (startX + delta*signum(deltaX)) + " " + (startY + 2*delta) +
                    " H" + (endX - delta*signum(deltaX)) + 
                    " A" + delta + " " +  delta + " 0 0 " + arc2 + " " + endX + " " + (startY + 3*delta) +
                    " V" + endY );
}
function connectElements(svg, path, startElem, endElem) {
    var svgContainer= $("#svgContainer");
    // if first element is lower than the second, swap!
    if(startElem.offset().top > endElem.offset().top){
        var temp = startElem;
        startElem = endElem;
        endElem = temp;
    }
    // get (top, left) corner coordinates of the svg container   
    var svgTop  = svgContainer.offset().top;
    var svgLeft = svgContainer.offset().left;
    // get (top, left) coordinates for the two elements
    var startCoord = startElem.offset();
    var endCoord   = endElem.offset();
    // calculate path's start (x,y)  coords
    // we want the x coordinate to visually result in the element's mid point
    var startX = startCoord.left + 0.5*startElem.outerWidth() - svgLeft;    // x = left offset + 0.5*width - svg's left offset
    var startY = startCoord.top  + startElem.outerHeight() - svgTop;        // y = top offset + height - svg's top offset
        // calculate path's end (x,y) coords
    var endX = endCoord.left + 0.5*endElem.outerWidth() - svgLeft;
    var endY = endCoord.top  - svgTop;
    // call function for drawing the path
    drawPath(svg, path, startX, startY, endX, endY);
}
$(document).ready(function() {
    // reset svg each time 
    $("#svg1").attr("height", "0");
    $("#svg1").attr("width", "0");
    connectAll();
});
$(window).resize(function () {
    // reset svg each time 
    $("#svg1").attr("height", "0");
    $("#svg1").attr("width", "0");
    connectAll();
});
function connectAll() {
connectElements($("#svg1"), $("#path1"), $("#ClientC-12"),$("#ClientC-8"));
connectElements($("#svg1"), $("#path2"), $("#ClientC-12"),$("#ClientC-8"));
connectElements($("#svg1"), $("#path3"), $("#ClientC-13"),$("#ClientC-12"));
connectElements($("#svg1"), $("#path4"), $("#ClientC-13"),$("#ClientC-8"));
connectElements($("#svg1"), $("#path5"), $("#ClientC-13"),$("#ClientC-8"));
connectElements($("#svg1"), $("#path6"), $("#ClientC-21"),$("#ClientC-8"));
connectElements($("#svg1"), $("#path7"), $("#ClientC-21"),$("#ClientC-8"));
connectElements($("#svg1"), $("#path8"), $("#ClientC-22"),$("#ClientC-8"));
connectElements($("#svg1"), $("#path9"), $("#ClientC-22"),$("#ClientC-8"));
connectElements($("#svg1"), $("#path10"), $("#ClientC-22"),$("#ClientC-21"));
connectElements($("#svg1"), $("#path11"), $("#ClientC-24"),$("#ClientC-8"));
connectElements($("#svg1"), $("#path12"), $("#ClientC-24"),$("#ClientC-21"));
connectElements($("#svg1"), $("#path13"), $("#ClientC-24"),$("#ClientC-8"));
connectElements($("#svg1"), $("#path14"), $("#ClientC-22"),$("#ClientC-21"));
connectElements($("#svg1"), $("#path15"), $("#ClientC-24"),$("#ClientC-21"));
connectElements($("#svg1"), $("#path16"), $("#ClientC-32"),$("#ClientC-29"));
connectElements($("#svg1"), $("#path17"), $("#ClientC-32"),$("#ClientC-29"));
connectElements($("#svg1"), $("#path18"), $("#ClientC-32"),$("#ClientC-29"));
connectElements($("#svg1"), $("#path19"), $("#ClientC-36"),$("#ClientC-29"));
connectElements($("#svg1"), $("#path20"), $("#ClientC-36"),$("#ClientC-29"));
connectElements($("#svg1"), $("#path21"), $("#ClientC-36"),$("#ClientC-29"));
connectElements($("#svg1"), $("#path22"), $("#ClientC-39"),$("#ClientC-29"));
connectElements($("#svg1"), $("#path23"), $("#ClientC-39"),$("#ClientC-29"));
connectElements($("#svg1"), $("#path24"), $("#ClientC-39"),$("#ClientC-29"));
connectElements($("#svg1"), $("#path25"), $("#ClientC-40"),$("#ClientC-8"));
connectElements($("#svg1"), $("#path26"), $("#ClientC-40"),$("#ClientC-29"));
connectElements($("#svg1"), $("#path27"), $("#ClientC-40"),$("#ClientC-29"));
connectElements($("#svg1"), $("#path28"), $("#ClientC-40"),$("#ClientC-29"));
connectElements($("#svg1"), $("#path29"), $("#ClientC-58"),$("#ClientC-54"));
connectElements($("#svg1"), $("#path30"), $("#ClientC-58"),$("#ClientC-54"));
connectElements($("#svg1"), $("#path31"), $("#ClientC-59"),$("#ClientC-58"));
connectElements($("#svg1"), $("#path32"), $("#ClientC-59"),$("#ClientC-54"));
connectElements($("#svg1"), $("#path33"), $("#ClientC-59"),$("#ClientC-54"));
connectElements($("#svg1"), $("#path34"), $("#ClientC-62"),$("#ClientC-54"));
connectElements($("#svg1"), $("#path35"), $("#ClientC-62"),$("#ClientC-54"));
connectElements($("#svg1"), $("#path36"), $("#ClientC-62"),$("#ClientC-54"));
connectElements($("#svg1"), $("#path37"), $("#ClientC-65"),$("#ClientC-54"));
connectElements($("#svg1"), $("#path38"), $("#ClientC-65"),$("#ClientC-54"));
connectElements($("#svg1"), $("#path39"), $("#ClientC-65"),$("#ClientC-54"));
connectElements($("#svg1"), $("#path40"), $("#ClientC-66"),$("#ClientC-45"));
connectElements($("#svg1"), $("#path41"), $("#ClientC-66"),$("#ClientC-54"));
connectElements($("#svg1"), $("#path42"), $("#ClientC-66"),$("#ClientC-54"));
connectElements($("#svg1"), $("#path43"), $("#ClientC-66"),$("#ClientC-54"));
connectElements($("#svg1"), $("#path44"), $("#ClientC-73"),$("#ClientC-71"));
connectElements($("#svg1"), $("#path45"), $("#ClientC-73"),$("#ClientC-71"));
connectElements($("#svg1"), $("#path46"), $("#ClientC-73"),$("#ClientC-71"));
connectElements($("#svg1"), $("#path47"), $("#ClientC-81"),$("#ClientC-79"));
connectElements($("#svg1"), $("#path48"), $("#ClientC-81"),$("#ClientC-79"));
connectElements($("#svg1"), $("#path49"), $("#ClientC-83"),$("#ClientC-79"));
connectElements($("#svg1"), $("#path50"), $("#ClientC-83"),$("#ClientC-79"));
connectElements($("#svg1"), $("#path51"), $("#ClientC-84"),$("#ClientC-79"));
connectElements($("#svg1"), $("#path52"), $("#ClientC-84"),$("#ClientC-79"));
connectElements($("#svg1"), $("#path53"), $("#ClientC-84"),$("#ClientC-83"));
connectElements($("#svg1"), $("#path54"), $("#ClientC-86"),$("#ClientC-84"));
connectElements($("#svg1"), $("#path55"), $("#ClientC-86"),$("#ClientC-79"));
connectElements($("#svg1"), $("#path56"), $("#ClientC-88"),$("#ClientC-79"));
connectElements($("#svg1"), $("#path57"), $("#ClientC-88"),$("#ClientC-84"));
connectElements($("#svg1"), $("#path58"), $("#ClientC-89"),$("#ClientC-88"));
connectElements($("#svg1"), $("#path59"), $("#ClientC-89"),$("#ClientC-79"));
connectElements($("#svg1"), $("#path60"), $("#ClientC-91"),$("#ClientC-79"));
connectElements($("#svg1"), $("#path61"), $("#ClientC-91"),$("#ClientC-88"));
connectElements($("#svg1"), $("#path62"), $("#ClientC-91"),$("#ClientC-89"));
connectElements($("#svg1"), $("#path63"), $("#ClientC-92"),$("#ClientC-88"));
connectElements($("#svg1"), $("#path64"), $("#ClientC-92"),$("#ClientC-89"));
connectElements($("#svg1"), $("#path65"), $("#ClientC-91"),$("#ClientC-89"));
connectElements($("#svg1"), $("#path66"), $("#ClientC-92"),$("#ClientC-91"));
connectElements($("#svg1"), $("#path67"), $("#ClientC-94"),$("#ClientC-88"));
connectElements($("#svg1"), $("#path68"), $("#ClientC-94"),$("#ClientC-79"));
connectElements($("#svg1"), $("#path69"), $("#ClientC-96"),$("#ClientC-83"));
connectElements($("#svg1"), $("#path70"), $("#ClientC-96"),$("#ClientC-94"));
connectElements($("#svg1"), $("#path71"), $("#ClientC-97"),$("#ClientC-96"));
connectElements($("#svg1"), $("#path72"), $("#ClientC-97"),$("#ClientC-88"));
connectElements($("#svg1"), $("#path73"), $("#ClientC-97"),$("#ClientC-94"));
connectElements($("#svg1"), $("#path74"), $("#ClientC-98"),$("#ClientC-88"));
connectElements($("#svg1"), $("#path75"), $("#ClientC-98"),$("#ClientC-94"));
connectElements($("#svg1"), $("#path76"), $("#ClientC-99"),$("#ClientC-29"));
connectElements($("#svg1"), $("#path77"), $("#ClientC-99"),$("#ClientC-79"));
connectElements($("#svg1"), $("#path78"), $("#ClientC-99"),$("#ClientC-94"));
connectElements($("#svg1"), $("#path79"), $("#ClientC-99"),$("#ClientC-96"));
connectElements($("#svg1"), $("#path80"), $("#ClientC-96"),$("#ClientC-94"));
connectElements($("#svg1"), $("#path81"), $("#ClientC-97"),$("#ClientC-96"));
connectElements($("#svg1"), $("#path82"), $("#ClientC-98"),$("#ClientC-97"));
connectElements($("#svg1"), $("#path83"), $("#ClientC-99"),$("#ClientC-98"));
connectElements($("#svg1"), $("#path84"), $("#ClientC-108"),$("#ClientC-106"));
connectElements($("#svg1"), $("#path85"), $("#ClientC-108"),$("#ClientC-106"));
connectElements($("#svg1"), $("#path86"), $("#ClientC-108"),$("#ClientC-106"));
connectElements($("#svg1"), $("#path87"), $("#ClientC-110"),$("#ClientC-106"));
connectElements($("#svg1"), $("#path88"), $("#ClientC-110"),$("#ClientC-106"));
connectElements($("#svg1"), $("#path89"), $("#ClientC-111"),$("#ClientC-110"));
connectElements($("#svg1"), $("#path90"), $("#ClientC-111"),$("#ClientC-106"));
connectElements($("#svg1"), $("#path91"), $("#ClientC-111"),$("#ClientC-106"));
connectElements($("#svg1"), $("#path92"), $("#ClientC-112"),$("#ClientC-110"));
connectElements($("#svg1"), $("#path93"), $("#ClientC-112"),$("#ClientC-106"));
connectElements($("#svg1"), $("#path94"), $("#ClientC-112"),$("#ClientC-106"));
connectElements($("#svg1"), $("#path95"), $("#ClientC-114"),$("#ClientC-110"));
connectElements($("#svg1"), $("#path96"), $("#ClientC-114"),$("#ClientC-106"));
connectElements($("#svg1"), $("#path97"), $("#ClientC-115"),$("#ClientC-113"));
connectElements($("#svg1"), $("#path98"), $("#ClientC-115"),$("#ClientC-106"));
connectElements($("#svg1"), $("#path99"), $("#ClientC-116"),$("#ClientC-110"));
connectElements($("#svg1"), $("#path100"), $("#ClientC-116"),$("#ClientC-106"));
connectElements($("#svg1"), $("#path101"), $("#ClientC-116"),$("#ClientC-113"));
connectElements($("#svg1"), $("#path102"), $("#ClientC-117"),$("#ClientC-110"));
connectElements($("#svg1"), $("#path103"), $("#ClientC-117"),$("#ClientC-106"));
connectElements($("#svg1"), $("#path104"), $("#ClientC-117"),$("#ClientC-106"));
connectElements($("#svg1"), $("#path105"), $("#ClientC-118"),$("#ClientC-29"));
connectElements($("#svg1"), $("#path106"), $("#ClientC-118"),$("#ClientC-106"));
connectElements($("#svg1"), $("#path107"), $("#ClientC-118"),$("#ClientC-106"));
connectElements($("#svg1"), $("#path108"), $("#ClientC-118"),$("#ClientC-110"));
connectElements($("#svg1"), $("#path109"), $("#ClientC-126"),$("#ClientC-124"));
connectElements($("#svg1"), $("#path110"), $("#ClientC-126"),$("#ClientC-124"));
connectElements($("#svg1"), $("#path111"), $("#ClientC-126"),$("#ClientC-124"));
connectElements($("#svg1"), $("#path112"), $("#ClientC-128"),$("#ClientC-126"));
connectElements($("#svg1"), $("#path113"), $("#ClientC-128"),$("#ClientC-124"));
connectElements($("#svg1"), $("#path114"), $("#ClientC-130"),$("#ClientC-124"));
connectElements($("#svg1"), $("#path115"), $("#ClientC-130"),$("#ClientC-128"));
connectElements($("#svg1"), $("#path116"), $("#ClientC-130"),$("#ClientC-126"));
connectElements($("#svg1"), $("#path117"), $("#ClientC-133"),$("#ClientC-124"));
connectElements($("#svg1"), $("#path118"), $("#ClientC-133"),$("#ClientC-128"));
connectElements($("#svg1"), $("#path119"), $("#ClientC-130"),$("#ClientC-128"));
connectElements($("#svg1"), $("#path120"), $("#ClientC-133"),$("#ClientC-130"));
connectElements($("#svg1"), $("#path121"), $("#ClientC-144"),$("#ClientC-141"));
connectElements($("#svg1"), $("#path122"), $("#ClientC-144"),$("#ClientC-141"));
connectElements($("#svg1"), $("#path123"), $("#ClientC-144"),$("#ClientC-141"));
connectElements($("#svg1"), $("#path124"), $("#ClientC-148"),$("#ClientC-141"));
connectElements($("#svg1"), $("#path125"), $("#ClientC-148"),$("#ClientC-141"));
connectElements($("#svg1"), $("#path126"), $("#ClientC-150"),$("#ClientC-141"));
connectElements($("#svg1"), $("#path127"), $("#ClientC-150"),$("#ClientC-141"));
connectElements($("#svg1"), $("#path128"), $("#ClientC-150"),$("#ClientC-141"));
connectElements($("#svg1"), $("#path129"), $("#ClientC-153"),$("#ClientC-141"));
connectElements($("#svg1"), $("#path130"), $("#ClientC-153"),$("#ClientC-150"));
connectElements($("#svg1"), $("#path131"), $("#ClientC-154"),$("#ClientC-141"));
connectElements($("#svg1"), $("#path132"), $("#ClientC-154"),$("#ClientC-150"));
connectElements($("#svg1"), $("#path133"), $("#ClientC-153"),$("#ClientC-150"));
connectElements($("#svg1"), $("#path134"), $("#ClientC-154"),$("#ClientC-153"));
connectElements($("#svg1"), $("#path135"), $("#ClientC-164"),$("#ClientC-162"));
connectElements($("#svg1"), $("#path136"), $("#ClientC-164"),$("#ClientC-162"));
connectElements($("#svg1"), $("#path137"), $("#ClientC-164"),$("#ClientC-162"));
connectElements($("#svg1"), $("#path138"), $("#ClientC-165"),$("#ClientC-164"));
connectElements($("#svg1"), $("#path139"), $("#ClientC-165"),$("#ClientC-164"));
connectElements($("#svg1"), $("#path140"), $("#ClientC-166"),$("#ClientC-162"));
connectElements($("#svg1"), $("#path141"), $("#ClientC-166"),$("#ClientC-162"));
connectElements($("#svg1"), $("#path142"), $("#ClientC-166"),$("#ClientC-162"));
connectElements($("#svg1"), $("#path143"), $("#ClientC-174"),$("#ClientC-172"));
connectElements($("#svg1"), $("#path144"), $("#ClientC-174"),$("#ClientC-172"));
connectElements($("#svg1"), $("#path145"), $("#ClientC-174"),$("#ClientC-172"));
connectElements($("#svg1"), $("#path146"), $("#ClientC-175"),$("#ClientC-174"));
connectElements($("#svg1"), $("#path147"), $("#ClientC-175"),$("#ClientC-174"));
connectElements($("#svg1"), $("#path148"), $("#ClientC-176"),$("#ClientC-172"));
connectElements($("#svg1"), $("#path149"), $("#ClientC-176"),$("#ClientC-172"));
connectElements($("#svg1"), $("#path150"), $("#ClientC-176"),$("#ClientC-172"));
connectElements($("#svg1"), $("#path151"), $("#ClientH-12"),$("#ClientH-10"));
connectElements($("#svg1"), $("#path152"), $("#ClientH-13"),$("#ClientH-10"));
connectElements($("#svg1"), $("#path153"), $("#ClientH-14"),$("#ClientH-10"));
connectElements($("#svg1"), $("#path154"), $("#ClientH-15"),$("#ClientH-10"));
connectElements($("#svg1"), $("#path155"), $("#ClientH-17"),$("#ClientH-10"));
connectElements($("#svg1"), $("#path156"), $("#ClientH-18"),$("#ClientH-10"));
connectElements($("#svg1"), $("#path157"), $("#ClientH-24"),$("#ClientH-22"));
connectElements($("#svg1"), $("#path158"), $("#ClientH-25"),$("#ClientH-22"));
connectElements($("#svg1"), $("#path159"), $("#ClientH-30"),$("#ClientH-28"));
connectElements($("#svg1"), $("#path160"), $("#ClientH-31"),$("#ClientH-28"));
connectElements($("#svg1"), $("#path161"), $("#EmailC-9"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path162"), $("#EmailC-10"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path163"), $("#EmailC-10"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path164"), $("#EmailC-11"),$("#EmailC-9"));
connectElements($("#svg1"), $("#path165"), $("#EmailC-11"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path166"), $("#EmailC-11"),$("#EmailC-10"));
connectElements($("#svg1"), $("#path167"), $("#EmailC-11"),$("#EmailC-10"));
connectElements($("#svg1"), $("#path168"), $("#EmailC-12"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path169"), $("#EmailC-12"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path170"), $("#EmailC-13"),$("#EmailC-9"));
connectElements($("#svg1"), $("#path171"), $("#EmailC-13"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path172"), $("#EmailC-13"),$("#EmailC-12"));
connectElements($("#svg1"), $("#path173"), $("#EmailC-13"),$("#EmailC-12"));
connectElements($("#svg1"), $("#path174"), $("#EmailC-14"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path175"), $("#EmailC-14"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path176"), $("#EmailC-15"),$("#EmailC-9"));
connectElements($("#svg1"), $("#path177"), $("#EmailC-15"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path178"), $("#EmailC-15"),$("#EmailC-14"));
connectElements($("#svg1"), $("#path179"), $("#EmailC-15"),$("#EmailC-14"));
connectElements($("#svg1"), $("#path180"), $("#EmailC-16"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path181"), $("#EmailC-16"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path182"), $("#EmailC-17"),$("#EmailC-9"));
connectElements($("#svg1"), $("#path183"), $("#EmailC-17"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path184"), $("#EmailC-17"),$("#EmailC-16"));
connectElements($("#svg1"), $("#path185"), $("#EmailC-17"),$("#EmailC-16"));
connectElements($("#svg1"), $("#path186"), $("#EmailC-18"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path187"), $("#EmailC-18"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path188"), $("#EmailC-19"),$("#EmailC-9"));
connectElements($("#svg1"), $("#path189"), $("#EmailC-19"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path190"), $("#EmailC-19"),$("#EmailC-18"));
connectElements($("#svg1"), $("#path191"), $("#EmailC-19"),$("#EmailC-18"));
connectElements($("#svg1"), $("#path192"), $("#EmailC-21"),$("#EmailC-9"));
connectElements($("#svg1"), $("#path193"), $("#EmailC-21"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path194"), $("#EmailC-21"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path195"), $("#EmailC-22"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path196"), $("#EmailC-22"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path197"), $("#EmailC-23"),$("#EmailC-9"));
connectElements($("#svg1"), $("#path198"), $("#EmailC-23"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path199"), $("#EmailC-23"),$("#EmailC-22"));
connectElements($("#svg1"), $("#path200"), $("#EmailC-23"),$("#EmailC-22"));
connectElements($("#svg1"), $("#path201"), $("#EmailC-25"),$("#EmailC-9"));
connectElements($("#svg1"), $("#path202"), $("#EmailC-25"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path203"), $("#EmailC-31"),$("#EmailC-29"));
connectElements($("#svg1"), $("#path204"), $("#EmailC-31"),$("#EmailC-29"));
connectElements($("#svg1"), $("#path205"), $("#EmailC-32"),$("#EmailC-29"));
connectElements($("#svg1"), $("#path206"), $("#EmailC-32"),$("#EmailC-29"));
connectElements($("#svg1"), $("#path207"), $("#EmailC-33"),$("#EmailC-29"));
connectElements($("#svg1"), $("#path208"), $("#EmailC-33"),$("#EmailC-29"));
connectElements($("#svg1"), $("#path209"), $("#EmailC-34"),$("#EmailC-29"));
connectElements($("#svg1"), $("#path210"), $("#EmailC-34"),$("#EmailC-29"));
connectElements($("#svg1"), $("#path211"), $("#EmailC-35"),$("#EmailC-29"));
connectElements($("#svg1"), $("#path212"), $("#EmailC-35"),$("#EmailC-29"));
connectElements($("#svg1"), $("#path213"), $("#EmailC-36"),$("#EmailC-29"));
connectElements($("#svg1"), $("#path214"), $("#EmailC-36"),$("#EmailC-29"));
connectElements($("#svg1"), $("#path215"), $("#EmailC-38"),$("#EmailC-29"));
connectElements($("#svg1"), $("#path216"), $("#EmailC-38"),$("#EmailC-29"));
connectElements($("#svg1"), $("#path217"), $("#EmailC-39"),$("#EmailC-29"));
connectElements($("#svg1"), $("#path218"), $("#EmailC-39"),$("#EmailC-29"));
connectElements($("#svg1"), $("#path219"), $("#EmailC-47"),$("#EmailC-44"));
connectElements($("#svg1"), $("#path220"), $("#EmailC-47"),$("#EmailC-44"));
connectElements($("#svg1"), $("#path221"), $("#EmailC-48"),$("#EmailC-47"));
connectElements($("#svg1"), $("#path222"), $("#EmailC-50"),$("#EmailC-47"));
connectElements($("#svg1"), $("#path223"), $("#EmailC-48"),$("#EmailC-47"));
connectElements($("#svg1"), $("#path224"), $("#EmailC-50"),$("#EmailC-47"));
connectElements($("#svg1"), $("#path225"), $("#EmailC-58"),$("#EmailC-56"));
connectElements($("#svg1"), $("#path226"), $("#EmailC-58"),$("#EmailC-56"));
connectElements($("#svg1"), $("#path227"), $("#EmailH-3"),$("#EmailH-1"));
connectElements($("#svg1"), $("#path228"), $("#EmailH-4"),$("#EmailH-1"));
connectElements($("#svg1"), $("#path229"), $("#EmailH-5"),$("#EmailH-1"));
connectElements($("#svg1"), $("#path230"), $("#EmailH-6"),$("#EmailH-1"));
connectElements($("#svg1"), $("#path231"), $("#EmailH-7"),$("#EmailH-1"));
connectElements($("#svg1"), $("#path232"), $("#EmailH-8"),$("#EmailH-1"));
connectElements($("#svg1"), $("#path233"), $("#EmailH-9"),$("#EmailH-1"));
connectElements($("#svg1"), $("#path234"), $("#slistC-35"),$("#slistC-34"));
connectElements($("#svg1"), $("#path235"), $("#slistC-35"),$("#slistC-32"));
connectElements($("#svg1"), $("#path236"), $("#slistC-36"),$("#slistC-35"));
connectElements($("#svg1"), $("#path237"), $("#slistC-36"),$("#slistC-35"));
connectElements($("#svg1"), $("#path238"), $("#slistC-37"),$("#slistC-34"));
connectElements($("#svg1"), $("#path239"), $("#slistC-37"),$("#slistC-32"));
connectElements($("#svg1"), $("#path240"), $("#slistC-37"),$("#slistC-32"));
connectElements($("#svg1"), $("#path241"), $("#slistC-38"),$("#slistC-34"));
connectElements($("#svg1"), $("#path242"), $("#slistC-38"),$("#slistC-32"));
connectElements($("#svg1"), $("#path243"), $("#slistC-39"),$("#slistC-34"));
connectElements($("#svg1"), $("#path244"), $("#slistC-39"),$("#slistC-32"));
connectElements($("#svg1"), $("#path245"), $("#slistC-46"),$("#slistC-45"));
connectElements($("#svg1"), $("#path246"), $("#slistC-46"),$("#slistC-43"));
connectElements($("#svg1"), $("#path247"), $("#slistC-46"),$("#slistC-32"));
connectElements($("#svg1"), $("#path248"), $("#slistC-46"),$("#slistC-43"));
connectElements($("#svg1"), $("#path249"), $("#slistC-47"),$("#slistC-45"));
connectElements($("#svg1"), $("#path250"), $("#slistC-47"),$("#slistC-43"));
connectElements($("#svg1"), $("#path251"), $("#slistC-47"),$("#slistC-43"));
connectElements($("#svg1"), $("#path252"), $("#slistC-48"),$("#slistC-43"));
connectElements($("#svg1"), $("#path253"), $("#slistC-48"),$("#slistC-45"));
connectElements($("#svg1"), $("#path254"), $("#slistC-48"),$("#slistC-43"));
connectElements($("#svg1"), $("#path255"), $("#slistC-49"),$("#slistC-45"));
connectElements($("#svg1"), $("#path256"), $("#slistC-49"),$("#slistC-43"));
connectElements($("#svg1"), $("#path257"), $("#slistC-56"),$("#slistC-55"));
connectElements($("#svg1"), $("#path258"), $("#slistC-56"),$("#slistC-53"));
connectElements($("#svg1"), $("#path259"), $("#slistC-56"),$("#slistC-32"));
connectElements($("#svg1"), $("#path260"), $("#slistC-56"),$("#slistC-53"));
connectElements($("#svg1"), $("#path261"), $("#slistC-57"),$("#slistC-55"));
connectElements($("#svg1"), $("#path262"), $("#slistC-57"),$("#slistC-53"));
connectElements($("#svg1"), $("#path263"), $("#slistC-57"),$("#slistC-53"));
connectElements($("#svg1"), $("#path264"), $("#slistC-58"),$("#slistC-55"));
connectElements($("#svg1"), $("#path265"), $("#slistC-58"),$("#slistC-53"));
connectElements($("#svg1"), $("#path266"), $("#slistC-64"),$("#slistC-62"));
connectElements($("#svg1"), $("#path267"), $("#slistC-64"),$("#slistC-62"));
connectElements($("#svg1"), $("#path268"), $("#slistC-64"),$("#slistC-62"));
connectElements($("#svg1"), $("#path269"), $("#slistC-65"),$("#slistC-62"));
connectElements($("#svg1"), $("#path270"), $("#slistC-65"),$("#slistC-62"));
connectElements($("#svg1"), $("#path271"), $("#slistC-65"),$("#slistC-64"));
connectElements($("#svg1"), $("#path272"), $("#slistC-66"),$("#slistC-62"));
connectElements($("#svg1"), $("#path273"), $("#slistC-66"),$("#slistC-62"));
connectElements($("#svg1"), $("#path274"), $("#slistC-68"),$("#slistC-62"));
connectElements($("#svg1"), $("#path275"), $("#slistC-68"),$("#slistC-62"));
connectElements($("#svg1"), $("#path276"), $("#slistC-68"),$("#slistC-66"));
connectElements($("#svg1"), $("#path277"), $("#slistC-69"),$("#slistC-62"));
connectElements($("#svg1"), $("#path278"), $("#slistC-69"),$("#slistC-66"));
connectElements($("#svg1"), $("#path279"), $("#slistC-70"),$("#slistC-66"));
connectElements($("#svg1"), $("#path280"), $("#slistC-73"),$("#slistC-66"));
connectElements($("#svg1"), $("#path281"), $("#slistC-68"),$("#slistC-66"));
connectElements($("#svg1"), $("#path282"), $("#slistC-69"),$("#slistC-68"));
connectElements($("#svg1"), $("#path283"), $("#slistC-70"),$("#slistC-69"));
connectElements($("#svg1"), $("#path284"), $("#slistC-73"),$("#slistC-66"));
connectElements($("#svg1"), $("#path285"), $("#slistC-79"),$("#slistC-77"));
connectElements($("#svg1"), $("#path286"), $("#slistC-79"),$("#slistC-77"));
connectElements($("#svg1"), $("#path287"), $("#slistC-81"),$("#slistC-77"));
connectElements($("#svg1"), $("#path288"), $("#slistC-81"),$("#slistC-79"));
connectElements($("#svg1"), $("#path289"), $("#slistC-82"),$("#slistC-81"));
connectElements($("#svg1"), $("#path290"), $("#slistC-82"),$("#slistC-81"));
connectElements($("#svg1"), $("#path291"), $("#slistC-83"),$("#slistC-77"));
connectElements($("#svg1"), $("#path292"), $("#slistC-83"),$("#slistC-79"));
connectElements($("#svg1"), $("#path293"), $("#slistC-81"),$("#slistC-79"));
connectElements($("#svg1"), $("#path294"), $("#slistC-83"),$("#slistC-82"));
connectElements($("#svg1"), $("#path295"), $("#slistC-85"),$("#slistC-77"));
connectElements($("#svg1"), $("#path296"), $("#slistC-91"),$("#slistC-89"));
connectElements($("#svg1"), $("#path297"), $("#slistC-91"),$("#slistC-89"));
connectElements($("#svg1"), $("#path298"), $("#slistC-93"),$("#slistC-89"));
connectElements($("#svg1"), $("#path299"), $("#slistC-93"),$("#slistC-89"));
connectElements($("#svg1"), $("#path300"), $("#slistC-93"),$("#slistC-91"));
connectElements($("#svg1"), $("#path301"), $("#slistC-94"),$("#slistC-89"));
connectElements($("#svg1"), $("#path302"), $("#slistC-94"),$("#slistC-93"));
connectElements($("#svg1"), $("#path303"), $("#slistC-94"),$("#slistC-93"));
connectElements($("#svg1"), $("#path304"), $("#slistC-95"),$("#slistC-89"));
connectElements($("#svg1"), $("#path305"), $("#slistC-95"),$("#slistC-91"));
connectElements($("#svg1"), $("#path306"), $("#slistC-93"),$("#slistC-91"));
connectElements($("#svg1"), $("#path307"), $("#slistC-95"),$("#slistC-94"));
connectElements($("#svg1"), $("#path308"), $("#slistC-97"),$("#slistC-89"));
connectElements($("#svg1"), $("#path309"), $("#slistH-3"),$("#slistH-1"));
connectElements($("#svg1"), $("#path310"), $("#slistH-4"),$("#slistH-1"));
connectElements($("#svg1"), $("#path311"), $("#EmailC-11"),$("#EmailH-3"));
connectElements($("#svg1"), $("#path312"), $("#ClientC-24"),$("#ClientH-13"));
connectElements($("#svg1"), $("#path313"), $("#slistC-68"),$("#slistH-4"));
connectElements($("#svg1"), $("#path314"), $("#EmailC-18"),$("#EmailH-7"));
connectElements($("#svg1"), $("#path315"), $("#slistC-56"),$("#slistH-8"));
connectElements($("#svg1"), $("#path316"), $("#ClientC-166"),$("#ClientH-30"));
connectElements($("#svg1"), $("#path317"), $("#slistC-48"),$("#slistH-4"));
connectElements($("#svg1"), $("#path318"), $("#ClientC-91"),$("#slistH-3"));
connectElements($("#svg1"), $("#path319"), $("#slistC-46"),$("#slistH-8"));
connectElements($("#svg1"), $("#path320"), $("#ClientC-148"),$("#ClientH-18"));
connectElements($("#svg1"), $("#path321"), $("#ClientC-62"),$("#ClientH-50"));
connectElements($("#svg1"), $("#path322"), $("#ClientC-62"),$("#ClientC-141"));
connectElements($("#svg1"), $("#path323"), $("#EmailC-23"),$("#EmailH-9"));
connectElements($("#svg1"), $("#path324"), $("#EmailC-36"),$("#EmailH-7"));
connectElements($("#svg1"), $("#path325"), $("#ClientC-88"),$("#ClientH-25"));
connectElements($("#svg1"), $("#path326"), $("#ClientC-116"),$("#EmailH-6"));
connectElements($("#svg1"), $("#path327"), $("#ClientC-144"),$("#ClientH-18"));
connectElements($("#svg1"), $("#path328"), $("#ClientC-153"),$("#EmailH-9"));
connectElements($("#svg1"), $("#path329"), $("#ClientC-81"),$("#ClientH-14"));
connectElements($("#svg1"), $("#path330"), $("#ClientC-150"),$("#EmailH-8"));
connectElements($("#svg1"), $("#path331"), $("#ClientC-108"),$("#EmailC-44"));
connectElements($("#svg1"), $("#path332"), $("#ClientC-108"),$("#EmailH-16"));
connectElements($("#svg1"), $("#path333"), $("#ClientC-84"),$("#EmailH-5"));
connectElements($("#svg1"), $("#path334"), $("#ClientC-96"),$("#EmailH-12"));
connectElements($("#svg1"), $("#path335"), $("#ClientC-96"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path336"), $("#ClientC-88"),$("#slistH-3"));
connectElements($("#svg1"), $("#path337"), $("#ClientC-111"),$("#EmailH-5"));
connectElements($("#svg1"), $("#path338"), $("#slistC-66"),$("#slistH-4"));
connectElements($("#svg1"), $("#path339"), $("#ClientC-13"),$("#EmailH-3"));
connectElements($("#svg1"), $("#path340"), $("#ClientC-144"),$("#EmailH-9"));
connectElements($("#svg1"), $("#path341"), $("#ClientC-92"),$("#slistH-4"));
connectElements($("#svg1"), $("#path342"), $("#ClientC-24"),$("#slistC-43"));
connectElements($("#svg1"), $("#path343"), $("#ClientC-24"),$("#slistH-10"));
connectElements($("#svg1"), $("#path344"), $("#slistC-81"),$("#slistH-3"));
connectElements($("#svg1"), $("#path345"), $("#ClientC-88"),$("#ClientH-22"));
connectElements($("#svg1"), $("#path346"), $("#ClientC-59"),$("#EmailH-3"));
connectElements($("#svg1"), $("#path347"), $("#slistC-47"),$("#slistH-4"));
connectElements($("#svg1"), $("#path348"), $("#ClientC-130"),$("#ClientH-31"));
connectElements($("#svg1"), $("#path349"), $("#slistC-95"),$("#slistH-4"));
connectElements($("#svg1"), $("#path350"), $("#ClientC-36"),$("#ClientH-39"));
connectElements($("#svg1"), $("#path351"), $("#ClientC-36"),$("#ClientC-79"));
connectElements($("#svg1"), $("#path352"), $("#EmailC-17"),$("#EmailH-6"));
connectElements($("#svg1"), $("#path353"), $("#ClientC-110"),$("#EmailH-12"));
connectElements($("#svg1"), $("#path354"), $("#ClientC-110"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path355"), $("#ClientC-112"),$("#EmailH-7"));
connectElements($("#svg1"), $("#path356"), $("#EmailC-39"),$("#EmailH-9"));
connectElements($("#svg1"), $("#path357"), $("#ClientC-98"),$("#slistH-4"));
connectElements($("#svg1"), $("#path358"), $("#ClientC-73"),$("#ClientH-24"));
connectElements($("#svg1"), $("#path359"), $("#ClientC-126"),$("#EmailH-5"));
connectElements($("#svg1"), $("#path360"), $("#ClientC-22"),$("#ClientH-13"));
connectElements($("#svg1"), $("#path361"), $("#EmailC-9"),$("#EmailH-1"));
connectElements($("#svg1"), $("#path362"), $("#EmailC-31"),$("#EmailH-3"));
connectElements($("#svg1"), $("#path363"), $("#ClientC-150"),$("#ClientH-18"));
connectElements($("#svg1"), $("#path364"), $("#ClientC-58"),$("#EmailC-56"));
connectElements($("#svg1"), $("#path365"), $("#ClientC-58"),$("#EmailH-18"));
connectElements($("#svg1"), $("#path366"), $("#EmailC-38"),$("#EmailH-8"));
connectElements($("#svg1"), $("#path367"), $("#EmailC-19"),$("#EmailH-7"));
connectElements($("#svg1"), $("#path368"), $("#ClientC-73"),$("#ClientH-22"));
connectElements($("#svg1"), $("#path369"), $("#EmailC-33"),$("#EmailH-5"));
connectElements($("#svg1"), $("#path370"), $("#slistC-57"),$("#slistH-4"));
connectElements($("#svg1"), $("#path371"), $("#ClientC-12"),$("#EmailC-56"));
connectElements($("#svg1"), $("#path372"), $("#ClientC-12"),$("#EmailH-18"));
connectElements($("#svg1"), $("#path373"), $("#ClientC-97"),$("#EmailH-5"));
connectElements($("#svg1"), $("#path374"), $("#ClientC-133"),$("#EmailH-8"));
connectElements($("#svg1"), $("#path375"), $("#ClientC-114"),$("#EmailH-6"));
connectElements($("#svg1"), $("#path376"), $("#EmailC-32"),$("#EmailH-4"));
connectElements($("#svg1"), $("#path377"), $("#ClientC-111"),$("#EmailH-4"));
connectElements($("#svg1"), $("#path378"), $("#slistC-64"),$("#slistH-4"));
connectElements($("#svg1"), $("#path379"), $("#ClientC-126"),$("#ClientH-17"));
connectElements($("#svg1"), $("#path380"), $("#EmailC-13"),$("#EmailH-4"));
connectElements($("#svg1"), $("#path381"), $("#EmailC-14"),$("#EmailH-5"));
connectElements($("#svg1"), $("#path382"), $("#ClientC-112"),$("#ClientH-15"));
connectElements($("#svg1"), $("#path383"), $("#EmailC-58"),$("#EmailH-8"));
connectElements($("#svg1"), $("#path384"), $("#EmailC-21"),$("#EmailH-8"));
connectElements($("#svg1"), $("#path385"), $("#slistC-83"),$("#slistH-4"));
connectElements($("#svg1"), $("#path386"), $("#ClientC-91"),$("#EmailH-5"));
connectElements($("#svg1"), $("#path387"), $("#EmailC-15"),$("#EmailH-5"));
connectElements($("#svg1"), $("#path388"), $("#ClientC-130"),$("#EmailH-9"));
connectElements($("#svg1"), $("#path389"), $("#EmailC-10"),$("#EmailH-3"));
connectElements($("#svg1"), $("#path390"), $("#ClientC-32"),$("#ClientC-124"));
connectElements($("#svg1"), $("#path391"), $("#ClientC-32"),$("#ClientH-45"));
connectElements($("#svg1"), $("#path392"), $("#ClientC-84"),$("#ClientH-14"));
connectElements($("#svg1"), $("#path393"), $("#ClientC-126"),$("#slistH-18"));
connectElements($("#svg1"), $("#path394"), $("#ClientC-126"),$("#slistC-89"));
connectElements($("#svg1"), $("#path395"), $("#ClientC-21"),$("#ClientH-13"));
connectElements($("#svg1"), $("#path396"), $("#EmailC-34"),$("#EmailH-6"));
connectElements($("#svg1"), $("#path397"), $("#ClientC-130"),$("#ClientH-28"));
connectElements($("#svg1"), $("#path398"), $("#ClientC-154"),$("#EmailH-8"));
connectElements($("#svg1"), $("#path399"), $("#EmailC-16"),$("#EmailH-6"));
connectElements($("#svg1"), $("#path400"), $("#ClientC-97"),$("#slistH-3"));
connectElements($("#svg1"), $("#path401"), $("#ClientC-166"),$("#ClientH-28"));
connectElements($("#svg1"), $("#path402"), $("#ClientC-117"),$("#EmailH-6"));
connectElements($("#svg1"), $("#path403"), $("#ClientC-84"),$("#slistH-18"));
connectElements($("#svg1"), $("#path404"), $("#ClientC-84"),$("#slistC-89"));
connectElements($("#svg1"), $("#path405"), $("#ClientC-22"),$("#slistC-32"));
connectElements($("#svg1"), $("#path406"), $("#ClientC-22"),$("#slistH-8"));
connectElements($("#svg1"), $("#path407"), $("#EmailC-47"),$("#EmailC-56"));
connectElements($("#svg1"), $("#path408"), $("#EmailC-47"),$("#EmailH-18"));
connectElements($("#svg1"), $("#path409"), $("#ClientC-99"),$("#ClientH-34"));
connectElements($("#svg1"), $("#path410"), $("#ClientC-118"),$("#ClientH-34"));
connectElements($("#svg1"), $("#path411"), $("#ClientC-130"),$("#slistH-3"));
connectElements($("#svg1"), $("#path412"), $("#EmailC-35"),$("#EmailC-44"));
connectElements($("#svg1"), $("#path413"), $("#EmailC-35"),$("#EmailH-16"));
connectElements($("#svg1"), $("#path414"), $("#slistC-65"),$("#slistH-4"));
connectElements($("#svg1"), $("#path415"), $("#slistC-38"),$("#slistH-4"));
connectElements($("#svg1"), $("#path416"), $("#ClientC-83"),$("#EmailH-12"));
connectElements($("#svg1"), $("#path417"), $("#ClientC-83"),$("#EmailC-7"));
connectElements($("#svg1"), $("#path418"), $("#EmailC-22"),$("#EmailH-9"));
connectElements($("#svg1"), $("#path419"), $("#ClientC-65"),$("#ClientC-106"));
connectElements($("#svg1"), $("#path420"), $("#ClientC-65"),$("#ClientH-41"));
connectElements($("#svg1"), $("#path421"), $("#EmailC-12"),$("#EmailH-4"));
connectElements($("#svg1"), $("#path422"), $("#ClientC-39"),$("#ClientH-12"));
connectElements($("#svg1"), $("#path423"), $("#ClientC-39"),$("#EmailH-4"));
connectElements($("#svg1"), $("#path424"), $("#ClientC-144"),$("#ClientH-53"));
connectElements($("#svg1"), $("#path425"), $("#ClientC-144"),$("#ClientC-172"));
connectElements($("#svg1"), $("#path426"), $("#ClientC-150"),$("#EmailH-9"));
connectElements($("#svg1"), $("#path427"), $("#ClientC-108"),$("#ClientH-15"));
connectElements($("#svg1"), $("#path428"), $("#ClientC-172"),$("#ClientH-53"));
connectElements($("#svg1"), $("#path429"), $("#slistC-89"),$("#slistH-18"));
connectElements($("#svg1"), $("#path430"), $("#ClientC-141"),$("#ClientH-50"));
connectElements($("#svg1"), $("#path431"), $("#EmailC-29"),$("#EmailH-14"));
connectElements($("#svg1"), $("#path432"), $("#EmailC-56"),$("#EmailH-18"));
connectElements($("#svg1"), $("#path433"), $("#EmailC-44"),$("#EmailH-16"));
connectElements($("#svg1"), $("#path434"), $("#ClientC-29"),$("#ClientH-34"));
connectElements($("#svg1"), $("#path435"), $("#ClientC-54"),$("#ClientH-36"));
connectElements($("#svg1"), $("#path436"), $("#slistC-77"),$("#slistH-16"));
connectElements($("#svg1"), $("#path437"), $("#slistC-32"),$("#slistH-8"));
connectElements($("#svg1"), $("#path438"), $("#ClientC-79"),$("#ClientH-39"));
connectElements($("#svg1"), $("#path439"), $("#ClientC-106"),$("#ClientH-41"));
connectElements($("#svg1"), $("#path440"), $("#EmailC-7"),$("#EmailH-12"));
connectElements($("#svg1"), $("#path441"), $("#slistC-43"),$("#slistH-10"));
connectElements($("#svg1"), $("#path442"), $("#slistC-62"),$("#slistH-14"));
connectElements($("#svg1"), $("#path443"), $("#slistC-53"),$("#slistH-12"));
connectElements($("#svg1"), $("#path444"), $("#ClientC-124"),$("#ClientH-45"));
}
